language: android
jdk: oraclejdk8
sudo: false
env:
  global:
    - TERM=dumb
android:
  components:
    - platform-tools
    - tools
    - tools
    - build-tools-25.0.0
    - android-25
    - extra-android-support
    - extra-android-m2repository
script: ./gradlew --info clean test
