sudo: true
language: android
jdk: oraclejdk8
env:
  global:
    - secure: "XevU0aQj+t9sW0z2TSGKpLrnPuq/yEN7sLMARMjUWTLFkmTd+krxODBIO9TSoPIa3ucMsPragbRf3VsAGfPRQhxHAACMRqLVM4/9YY+Jm4AUm6bN6hxZdsKjOJHhR5+Er0UOmqdlaVNomQHjHSVnskKtNDspBOSg7I6YTZqHAjisotEy+dn+XLyZl82AQ/JbLn2weL9Je0DT4JijgfWQS/m8nYxUUqQxiIC4n++oNkkH7LZ+JxEtGTjudeJQHGUBM5MyMRypU3iAdOX6/T6YxdAdfXcFpjBmM++oOAzigvFSAVO7L81Y8FQ6jZnlZgxzFwTCEpkJZbkosKYzpxh6QZIMW4GVcJH4gdWqyWzYNsG2RXZFJBEsmzbRdCrdYzM85BejkwMG9T1+9aFkio0/kgklkUHuDd1QPeIzenkECslQWTLN16GkGud5mX+6heXw2okj8tQ2HQXaCzR08OZWtImNeBqfFx+8/GJ7ThcN8GXB/iC4GutQGKxDNa1K7tjWtousiBJFKathLTHsiVry//UUMdavjwsouYtRaRzS9oVcHBssg+T0+PHW0VJYEE6tTg0Eg7IiyyLJhvdQNLj5wkAgzzGuLt8POcXkb7MhMlTtrfHPyAoPHStedhVJe4NwYPfw+7oaF+BUeMgdimqGFvbdZ8UEdbKsdMzuxLKc6c4="
    - secure: "ojdgDuyKu/ti4In8T/iYyxFy8nlkhncPxnaYvrfQtpdeGumt51wAfea80PpYQEuff/aFm5kpSmGFwshRKyEG2XeRW3Nb/zUQkPq2vBzXdpugZ6VeXTW7HE0XpIl0E6jmb+dXcO4sTMHDXWFMfOzdk0vfGotqD96BAEj47KVFNjc2CpHQnu0f0JAyOE10lqxhH57pek7XFhJvgpb0Qc18Q0ZXYFJwOFr5IufJZ5JNy4/EibtoTRXRCBcr+084kZbZXOWhhqXe2uU+i2gm/U2qfEHcJvgANhKjxZppTtKvimJ0dc8SuS4I0B0vuoaOAeuEVaeG9B3S3a5wW4qm9jnmTsz8ktmHrzVj0lYxG7XL8WxjEH7MlZrNWFynylhMNZDuqBuvK0jKo9eDuB6JZMI6dJ1i9yE7+MkDBt9ChCXAbbVFhAG9UO5N1bK+Q+DyRc5rhPa8Gq/yOt6b4q8Angf7euyafNfTRlbcvk11NcFQ6ySBKJJsdG8JXrjDpdtOXRiDjtKpL8mYGkhjpCaJr23ap8bkO38a4h4q74alATAwSYVVC30cu5GxXveoO5KQfXASEfcXOj+E7+3eC0KXmTxEaIZ+/30x4fBi4A5KczCeIWRv4AF3RHCzsLskcTp9L682q4/jED+yxHJDFFNf26N0TxAqAo6oDXjYImelyVqv3R4="
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra-android-support
    - extra-android-m2repository
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -skin WXGA720 -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 60
  - adb shell input keyevent 82
script: ./gradlew --info clean lint test connectedAndroidTest
after_success: ./deploy_snapshot.sh
